name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine package version from tag (if present)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "PKG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore KqlToSql.sln

      - name: Pack KqlToSql
        run: |
          if [ -n "${PKG_VERSION}" ]; then
            echo "Packing version ${PKG_VERSION}"
            dotnet pack src/KqlToSql/KqlToSql.csproj -c Release -o out -p:ContinuousIntegrationBuild=true -p:PackageVersion=${PKG_VERSION}
          else
            echo "Packing with project version"
            dotnet pack src/KqlToSql/KqlToSql.csproj -c Release -o out -p:ContinuousIntegrationBuild=true
          fi

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo "❌ Missing NUGET_API_KEY secret. Set it in repo settings -> Secrets and variables -> Actions." >&2
            exit 1
          fi
          dotnet nuget push "out/*.nupkg" \
            --api-key "$NUGET_API_KEY" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

